import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SessionProvider from '@/components/Provider/SessionProvider';
import ClientProviders from '@/components/Provider/ClientProvider';
import { getServerSession } from 'next-auth';
import { authOption } from '@/pages/api/auth/[...nextauth]';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOption);
	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionProvider session={session}>
					<ClientProviders>{children}</ClientProviders>
				</SessionProvider>
			</body>
		</html>
	);
}
